pretrained_model: ./models/deeplabv2_resnet101_COCO_init.pth
class_weight_flag: True
batch_size: 5
num_workers: 0
max_epoch: 1000
learning_rate: 0.00025
n_classes: 8
writer_flag: True
result_path: ./result_deeplab

