train_mode: full
model: SegNetBasic

class_weight_flag: True        # if you use class weight to calculate cross entropy or not
flip_label: True               # if you sometimes flip real label and fake label or not
noisy_label_: True             # if you use noisy label for real and fake or not
writer_flag: True              # if you use tensorboardx or not
gaussian: True                 # if you add gaussian noise to the input of discriminator or not
one_label_smooth: False        # if you change only real label for noisy label
pre_knowledge: True

in_channel: 3
n_classes: 8
height: 256
width: 320
loss_weight: 1.0
batch_size: 30
num_workers: 4
max_epoch: 200
full_epoch: 200                  # how many epochs do you want to set for surpervised learning
adv_epoch: 0                   # how many epochs do you want to set for adversarial learning
learning_rate: 0.0001
learning_rate_d: 0.0000001

real_label: 0.8
fake_label: 0.2
flip_label_th: 0.1               # threshold to determine if the labels of real and fake are flipped.
d_th: 0.4                        # threshold for the output of discriminator network when semi-supervised training
adv_weight: 0.001
semi_weight: 0.1


result_path: ./segnet_full
pretrain_model: 
labeled_data: ./part-affordance-dataset/train_with_label_3to1.csv
unlabeled_data: ./part-affordance-dataset/train_without_label_3to1.csv
test_data: ./part-affordance-dataset/test.csv
