class_weight_flag: True
noisy_label_flag: True
batch_size: 10
num_workers: 0
max_epoch: 300
learning_rate: 0.001
learning_rate_d: 0.0000001
n_classes: 8
writer_flag: True
result_path: ./result_segnet
labeled_data: ./part-affordance-dataset/train_with_label_4to1.csv
unlabeled_data: ./part-affordance-dataset/train_without_label_4to1.csv
test_data: ./part-affordance-dataset/test.csv

# not use specific tech in D